//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kardinal.Net.Web.Authorization.Permissions.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kardinal.Net.Web.Authorization.Permissions.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updating user data with the authority.
        /// </summary>
        internal static string AUTHORIZATION_ADDING_USER_DETAILS {
            get {
                return ResourceManager.GetString("AUTHORIZATION_ADDING_USER_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid access token: [{status}: {message}].
        /// </summary>
        internal static string AUTHORIZATION_ERROR_INVALID_TOKEN {
            get {
                return ResourceManager.GetString("AUTHORIZATION_ERROR_INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid access token: Wrong format!.
        /// </summary>
        internal static string AUTHORIZATION_ERROR_TOKEN_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("AUTHORIZATION_ERROR_TOKEN_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to update system user: {msg}.
        /// </summary>
        internal static string AUTHORIZATION_ERROR_UPDATE_SYSTEM_USER {
            get {
                return ResourceManager.GetString("AUTHORIZATION_ERROR_UPDATE_SYSTEM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user {usr} is authorized to access the {path} endpoint..
        /// </summary>
        internal static string AUTHORIZATION_USER_AUTHORIZED {
            get {
                return ResourceManager.GetString("AUTHORIZATION_USER_AUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authorized user under master authority..
        /// </summary>
        internal static string AUTHORIZATION_USER_ISROOT {
            get {
                return ResourceManager.GetString("AUTHORIZATION_USER_ISROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unauthorized user..
        /// </summary>
        internal static string AUTHORIZATION_USER_UNHAUTHORIZED {
            get {
                return ResourceManager.GetString("AUTHORIZATION_USER_UNHAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validating access token..
        /// </summary>
        internal static string AUTHORIZATION_VALIDATING_TOKEN {
            get {
                return ResourceManager.GetString("AUTHORIZATION_VALIDATING_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anonymous access permission should not contain a declaration of required permissions..
        /// </summary>
        internal static string ERROR_PERMISSION_DECLARATION_NOT_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_PERMISSION_DECLARATION_NOT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a At least one permission statement is required for the type of validation entered..
        /// </summary>
        internal static string ERROR_PERMISSION_DECLARATION_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_PERMISSION_DECLARATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user {usr} does not have one of the required permissions for this service: {pems}.
        /// </summary>
        internal static string ERROR_PERMISSION_MISSING_MULTI_LOGGER {
            get {
                return ResourceManager.GetString("ERROR_PERMISSION_MISSING_MULTI_LOGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user {usr} does not have any of the necessary permissions to access this service. At least one permission is required: {pem}.
        /// </summary>
        internal static string ERROR_PERMISSION_MISSING_SINGLE_LOGGER {
            get {
                return ResourceManager.GetString("ERROR_PERMISSION_MISSING_SINGLE_LOGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The permission-based authorization service was not found..
        /// </summary>
        internal static string ERROR_PERMISSION_SERVICE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_PERMISSION_SERVICE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anonymous access to endpoint {endpoint} authorized by remote requester {ipAddress}..
        /// </summary>
        internal static string PERMISSION_AUTHORIZATION_ANNONYMOUS {
            get {
                return ResourceManager.GetString("PERMISSION_AUTHORIZATION_ANNONYMOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unauthorized access..
        /// </summary>
        internal static string UNAUTHORIZED_DEFAULT_MESSAGE {
            get {
                return ResourceManager.GetString("UNAUTHORIZED_DEFAULT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid access token..
        /// </summary>
        internal static string UNAUTHORIZED_INVALID_TOKEN {
            get {
                return ResourceManager.GetString("UNAUTHORIZED_INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user {userName} doesn&apos;t have permissions to access this service..
        /// </summary>
        internal static string UNAUTHORIZED_MISSING_PERMISSIONS {
            get {
                return ResourceManager.GetString("UNAUTHORIZED_MISSING_PERMISSIONS", resourceCulture);
            }
        }
    }
}
