//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kardinal.Net.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kardinal.Net.Web.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The background task host has been initialized..
        /// </summary>
        internal static string DEBUG_BACKGROUND_TASK_HOST_START {
            get {
                return ResourceManager.GetString("DEBUG_BACKGROUND_TASK_HOST_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The background task host has terminated..
        /// </summary>
        internal static string DEBUG_BACKGROUND_TASK_HOST_STOP {
            get {
                return ResourceManager.GetString("DEBUG_BACKGROUND_TASK_HOST_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Api Service.
        /// </summary>
        internal static string DEFAULT_SERVICE_NAME {
            get {
                return ResourceManager.GetString("DEFAULT_SERVICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed while executing background task {task}: {message}.
        /// </summary>
        internal static string ERROR_BACKGROUND_TASK_FAIL {
            get {
                return ResourceManager.GetString("ERROR_BACKGROUND_TASK_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The background task to be performed cannot be null..
        /// </summary>
        internal static string ERROR_BACKGROUND_TASK_NULL {
            get {
                return ResourceManager.GetString("ERROR_BACKGROUND_TASK_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It is not possible to use Kestrel and IIS integration simultaneously..
        /// </summary>
        internal static string ERROR_CANT_USE_BOTH_KESTREL_IIS_INTEGRATION {
            get {
                return ResourceManager.GetString("ERROR_CANT_USE_BOTH_KESTREL_IIS_INTEGRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The certificate entered was not found at [{path}]..
        /// </summary>
        internal static string ERROR_CERTIFICATE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_CERTIFICATE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The certificate [{thumbprint}] does not have a private key assigned..
        /// </summary>
        internal static string ERROR_CERTIFICATE_PRIVATE_KEY_MISSING {
            get {
                return ResourceManager.GetString("ERROR_CERTIFICATE_PRIVATE_KEY_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Given content root [$[CONTENT_ROOT]] is not a valid directory!.
        /// </summary>
        internal static string ERROR_CONTENT_ROOT_INVALID {
            get {
                return ResourceManager.GetString("ERROR_CONTENT_ROOT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The service certificate location is null or invalid..
        /// </summary>
        internal static string ERROR_NULL_EMPTY_CERTIFICATE_PATH {
            get {
                return ResourceManager.GetString("ERROR_NULL_EMPTY_CERTIFICATE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The service $[SERVICE_NAME] was not found! Check that the service has been properly implemented and registered!.
        /// </summary>
        internal static string ERROR_SERVICE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_SERVICE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The service is shutting down....
        /// </summary>
        internal static string FINALIZING_SERVICE {
            get {
                return ResourceManager.GetString("FINALIZING_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Initializing service {service} in environment {environment} [{processId}]..
        /// </summary>
        internal static string INITIALIZATION_APP_INFO {
            get {
                return ResourceManager.GetString("INITIALIZATION_APP_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Initialization Complete.
        /// </summary>
        internal static string INITIALIZATION_COMPLETE {
            get {
                return ResourceManager.GetString("INITIALIZATION_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Using base directory {BASEPATH}.
        /// </summary>
        internal static string INITIALIZE_BASEPATH {
            get {
                return ResourceManager.GetString("INITIALIZE_BASEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Using IIS Integration.
        /// </summary>
        internal static string INITIALIZE_IIS_INTEGRATION {
            get {
                return ResourceManager.GetString("INITIALIZE_IIS_INTEGRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Listening to requests in {LISTENING_URL}.
        /// </summary>
        internal static string LISTENING_URL {
            get {
                return ResourceManager.GetString("LISTENING_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The service ended with the code {code}..
        /// </summary>
        internal static string SERVICE_FINALIZED {
            get {
                return ResourceManager.GetString("SERVICE_FINALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The request can be continued..
        /// </summary>
        internal static string STATUS_CODE_100 {
            get {
                return ResourceManager.GetString("STATUS_CODE_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Switching protocol..
        /// </summary>
        internal static string STATUS_CODE_101 {
            get {
                return ResourceManager.GetString("STATUS_CODE_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The request has succeeded..
        /// </summary>
        internal static string STATUS_CODE_200 {
            get {
                return ResourceManager.GetString("STATUS_CODE_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The request has been fulfilled and resulted in a new resource being created..
        /// </summary>
        internal static string STATUS_CODE_201 {
            get {
                return ResourceManager.GetString("STATUS_CODE_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The request has been accepted for processing, but the processing has not been completed..
        /// </summary>
        internal static string STATUS_CODE_202 {
            get {
                return ResourceManager.GetString("STATUS_CODE_202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The returned metainformation in the entity-header is not the definitive set as available from the origin server, but is gathered from a local or a third-party copy..
        /// </summary>
        internal static string STATUS_CODE_203 {
            get {
                return ResourceManager.GetString("STATUS_CODE_203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server has fulfilled the request but does not need to return an entity-body, and might want to return updated metainformation..
        /// </summary>
        internal static string STATUS_CODE_204 {
            get {
                return ResourceManager.GetString("STATUS_CODE_204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server has fulfilled the request and the user agent SHOULD reset the document view which caused the request to be sent..
        /// </summary>
        internal static string STATUS_CODE_205 {
            get {
                return ResourceManager.GetString("STATUS_CODE_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server has fulfilled the partial GET request for the resource..
        /// </summary>
        internal static string STATUS_CODE_206 {
            get {
                return ResourceManager.GetString("STATUS_CODE_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Multiple responses available..
        /// </summary>
        internal static string STATUS_CODE_300 {
            get {
                return ResourceManager.GetString("STATUS_CODE_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The requested resource has been moved to a new address..
        /// </summary>
        internal static string STATUS_CODE_301 {
            get {
                return ResourceManager.GetString("STATUS_CODE_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The requested resource has been temporarily moved to another address..
        /// </summary>
        internal static string STATUS_CODE_302 {
            get {
                return ResourceManager.GetString("STATUS_CODE_302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The request was not accepted due to missing or not validated data. Check the content of the request..
        /// </summary>
        internal static string STATUS_CODE_400 {
            get {
                return ResourceManager.GetString("STATUS_CODE_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The request was not authorized. Check if the session is active, the access token has been informed or if the active user has authorization to access this service..
        /// </summary>
        internal static string STATUS_CODE_401 {
            get {
                return ResourceManager.GetString("STATUS_CODE_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Access to the requested service is not allowed..
        /// </summary>
        internal static string STATUS_CODE_403 {
            get {
                return ResourceManager.GetString("STATUS_CODE_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The requested service or resource was not found..
        /// </summary>
        internal static string STATUS_CODE_404 {
            get {
                return ResourceManager.GetString("STATUS_CODE_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The method specified in the request is not allowed for the requested resource..
        /// </summary>
        internal static string STATUS_CODE_405 {
            get {
                return ResourceManager.GetString("STATUS_CODE_405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request..
        /// </summary>
        internal static string STATUS_CODE_406 {
            get {
                return ResourceManager.GetString("STATUS_CODE_406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Proxy authentication is required before completing the request..
        /// </summary>
        internal static string STATUS_CODE_407 {
            get {
                return ResourceManager.GetString("STATUS_CODE_407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The client did not produce a request within the time that the server was prepared to wait..
        /// </summary>
        internal static string STATUS_CODE_408 {
            get {
                return ResourceManager.GetString("STATUS_CODE_408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The request could not be completed due to a conflict with the current state of the resource..
        /// </summary>
        internal static string STATUS_CODE_409 {
            get {
                return ResourceManager.GetString("STATUS_CODE_409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The requested resource is no longer available at the server and no forwarding address is known..
        /// </summary>
        internal static string STATUS_CODE_410 {
            get {
                return ResourceManager.GetString("STATUS_CODE_410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server refuses to accept the requests without a defined Content- Length..
        /// </summary>
        internal static string STATUS_CODE_411 {
            get {
                return ResourceManager.GetString("STATUS_CODE_411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server is refusing to process a request because the request entity is larger than the server is willing or able to process.
        /// </summary>
        internal static string STATUS_CODE_413 {
            get {
                return ResourceManager.GetString("STATUS_CODE_413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server is refusing to service the request because the Request-URI is longer than the server is willing to interpret..
        /// </summary>
        internal static string STATUS_CODE_414 {
            get {
                return ResourceManager.GetString("STATUS_CODE_414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server is refusing to service the request because the entity of the request is in a format not supported by the requested resource for the requested method..
        /// </summary>
        internal static string STATUS_CODE_415 {
            get {
                return ResourceManager.GetString("STATUS_CODE_415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a I&apos;m a teapot..
        /// </summary>
        internal static string STATUS_CODE_418 {
            get {
                return ResourceManager.GetString("STATUS_CODE_418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server encountered an unexpected condition which prevented it from fulfilling the request..
        /// </summary>
        internal static string STATUS_CODE_500 {
            get {
                return ResourceManager.GetString("STATUS_CODE_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server does not support the functionality required to fulfill the request..
        /// </summary>
        internal static string STATUS_CODE_501 {
            get {
                return ResourceManager.GetString("STATUS_CODE_501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server, while acting as a gateway or proxy, received an invalid response from the upstream server it accessed in attempting to fulfill the request..
        /// </summary>
        internal static string STATUS_CODE_502 {
            get {
                return ResourceManager.GetString("STATUS_CODE_502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server is currently unable to handle the request due to a temporary overloading or maintenance of the server..
        /// </summary>
        internal static string STATUS_CODE_503 {
            get {
                return ResourceManager.GetString("STATUS_CODE_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server, while acting as a gateway or proxy, did not receive a timely response from the upstream server..
        /// </summary>
        internal static string STATUS_CODE_504 {
            get {
                return ResourceManager.GetString("STATUS_CODE_504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The server does not support, or refuses to support, the HTTP protocol version that was used in the request message..
        /// </summary>
        internal static string STATUS_CODE_505 {
            get {
                return ResourceManager.GetString("STATUS_CODE_505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The policy for accessing the resource has not been met in the request..
        /// </summary>
        internal static string STATUS_CODE_510 {
            get {
                return ResourceManager.GetString("STATUS_CODE_510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Network authentication is required before proceeding..
        /// </summary>
        internal static string STATUS_CODE_511 {
            get {
                return ResourceManager.GetString("STATUS_CODE_511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknow response $[VALUE]..
        /// </summary>
        internal static string STATUS_CODE_UNKNOW {
            get {
                return ResourceManager.GetString("STATUS_CODE_UNKNOW", resourceCulture);
            }
        }
    }
}
